/*
 * @Author       : jry
 * @Description  :
 * @version      : 4.0
 * @Date         : 2024-08-28 23:05:58
 * @LastAuthor   : jry
 * @lastTime     : 2024-08-28 23:05:58
 * @FilePath     : /uview-plus/libs/config/props/code.js
 */
export default {
    // code 组件
    code: {
        seconds: 60,
        startText: '获取验证码',
        changeText: 'X秒重新获取',
        endText: '重新获取',
        keepRunning: false,
        uniqueKey: ''
    }
} as UTSJSONObject
