/*
 * @Author       : jry
 * @Description  :
 * @version      : 4.0
 * @Date         : 2024-04-22 16:44:21
 * @LastAuthor   : jry
 * @lastTime     : 2024-08-28 11:05:25
 * @FilePath     : /uview-plus/libs/config/props/gap.js
 */
export default {
    // gap组件
    gap: {
        bgColor: 'transparent',
        height: '20',
        marginTop: '0',
        marginBottom: '0',
        customStyle: {}
    }
} as UTSJSONObject
