/*
 * @Author       : jry
 * @Description  :
 * @version      : 4.0
 * @Date         : 2024-04-22 16:44:21
 * @LastAuthor   : jry
 * @lastTime     : 2024-08-28 16:59:00
 * @FilePath     : /uview-plus/libs/config/props/transition.js
 */
export default {
    // transition动画组件的props
    transition: {
        show: false,
        mode: 'fade',
        duration: 300,
        timingFunction: 'ease-out'
    } as UTSJSONObject
}
