/*
 * @Author       : jry
 * @Description  :
 * @version      : 4.0
 * @Date         : 2024-12-23 11:27:21
 * @LastAuthor   : jry
 * @lastTime     : 2024-12-23 11:27:21
 * @FilePath     : /uview-plus/libs/config/props/alert
 */
export default {
    // alert警告组件
    alert: {
        title: '',
        type: 'warning',
        description: '',
        closable: false,
        showIcon: false,
        effect: 'light',
        center: false,
        fontSize: 14
    }
} as UTSJSONObject
