import { defineMixin } from '../../libs/vue.uts'
import defProps from '../../libs/config/props.uts'
let cellGroup = defProps['cellGroup'] as UTSJSONObject

export const props = defineMixin({
    props: {
        // 分组标题
        title: {
            type: String,
            default: cellGroup['title']
        },
        // 是否显示外边框
        border: {
            type: Boolean,
            default: cellGroup['border']
        }
    }
})
