/*
 * @Author       : jry,jry
 * @Description  :
 * @version      : 3.0
 * @Date         : 2024-04-22 16:44:21
 * @LastAuthor   : jry
 * @lastTime     : 2024-08-20 14:20:58
 * @FilePath     : /uview-plus/libs/config/props/col.js
 */
export default {
    // col 组件
    col: {
        span: '12',
        offset: '0',
        justify: 'start',
        align: 'stretch',
        textAlign: 'left'
    }
} as UTSJSONObject
